export {default as SignUp} from './SignUp/Container'
export {default as SignIn} from './SignIn/Container'
export {default as Profile} from './Profile/Container'
export {default as EditPage} from './EditPage/container'
export {default as Settings} from './Settings/container'